Repository w3c/trace-context, pull requests merged in 2019-04, with the labels that each got.

#259 Changes to wording, structure, grammar and spelling
  .gitignore
  index.html
  spec/01-abstract.md
  spec/10-overview.md
  spec/40-other-protocols.md
  spec/50-privacy.md
Labels: discuss-next-meeting

#248 Make tracestate limit the responsibility of a platform
  spec/20-http_header_format.md
  spec/21-http_header_format_rationale.md
Labels: discuss-next-meeting, substantial

#257 describe what invalid means
  spec/20-http_header_format.md
Labels: editorial

#258 added potential privacy risk
  spec/50-privacy.md
Labels: privacy

#260 traceparent restart should require tracestate cleanup rationale
  spec/20-http_header_format.md
  spec/21-http_header_format_rationale.md
Labels: editorial

#282 lines rewrap
  .gitignore
  .vscode/settings.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  spec/01-abstract.md
  spec/10-overview.md
  spec/20-http_header_format.md
  spec/21-http_header_format_rationale.md
  spec/40-other-protocols.md
  spec/50-privacy.md
  spec/51-security.md
Labels: editorial
