Repository w3c/trace-context, pull requests merged in 2019-01, with the labels that each got.

#225 Grammar, Spelling and wording
  spec/30-processing-model.md
Labels: editorial, trace-context

#230 Fix link
  README.md
Labels: editorial, ready for review

#229 use the lower case HEXDIGLC rule in abnf definition
  spec/20-http_header_format.md
Labels: ready for review

#224 - Fixes minor spelling- and grammar mistakes
  .gitignore
  spec/01-abstract.md
Labels: editorial, ready for review
